[package]
name = "markov"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
console_error_panic_hook = "0.1.7"
nalgebra = { version = "0.34.1" }
rand = { version = "0.9.2", default-features = false, features = ["small_rng"] }
wasm-bindgen = "0.2.106"

